### ISSUE TITLE
very slow in default config

### ISSUE THREAD

**Issue by r3dvorak** [artwork-software/artwork#198]
Hi there, 
great stuff, thank you for making it open source! 
I am fairly new to sail & laravel - using all your defaults, the installation works fine, but the admin panel is extremely slow - we are talking 20+ seconds when changing from Dashboard to Projects or anywhere else.
This is the case on local installation under Windows using Ubuntu 22.04 & WSL2. Same for a quick test I ran on a 2 vCPU, 4GB RAM Hetzner Cloud with Ubuntu 22.04.
Any pointers?

I did turn the debugbar off with DEBUGBAR_ENABLED = FALSE

Thanks
Richard

**Comment by Muelle96** [comment]
Hi r3dvorak,

the local installation under windows can be slower because then it needs to run a virtual linux core which decreases the performance. But it still shouldn't decrease the performance this much.

On your second test with these specs it should run fine. We have a test environment that has the same specs and it runs fine. 

Maybe there are some error logs that tell us why it is running this slow?

**Comment by Muelle96** [comment]
Yeah, that shouldnt be the case. We tested it on our systems again, and it did not lead to the problems you have. Maybe there went something wrong, when initializing the project. Did you use any other commands to start it? To solve the error i would ask you to try it from scratch one more time and follow the readme closely. If there are more errors you are encountering, let me know :)
