### ISSUE TITLE
what are the default credentials

### ISSUE THREAD

**Issue by SLINIcraftet204** [artwork-software/artwork#225]
Hey, I've installed artwork on a clean and fresh Ubuntu instance with the install script. Now my Problem is, what are the default login credentials because I can't find any information about it and can't login to use artwork.
![image](https://github.com/artwork-software/artwork/assets/45763476/44bca301-d710-438e-bbd3-0df2b0820942)

Hope for any help.
Kind regards Nils

(edit): and a complete documentation for a complete installation would be nice because I must search myself for all informations like how to setup SSL correctly (thats not working too) or how to set the privacy policy and imprint. Why is there a sail documentation, where do I find all configs and so on......

**Comment by Muelle96** [comment]
Hey Nils,

if you already seeded the database, the login for the test-users are in AuthUserSeeder.php as a shortcut for you: max.mustermann@kampnagel.de PW: TestPass1234!$ is the admin user that can see all of the tool.

these will change in the near future, if you havent seeded the database a "setup" screen should appear were you can set the login data for your admin account. IMPROTANT: To be able to invite new emails/users to artwork you will need to set the mail config in the env-file to your smtp server or service before doing so, otherwise no email will be send.

We will deliver a full documentation soon, right now we are still in development of version 1.0. I am sorry, that you will have to wait some time, but now you should at least get into the tool. 

Feel free to communicate if you get into some new issues :)

**Comment by SLINIcraftet204** [comment]
Hey, tanks for your reply the Login worked, I don't know if this is a Bug, I've installed it standalone on my Ubuntu Server with the script and after the script was finished, I had no chance to set it up. The webpage directly shows the Login Window.

**Comment by Muelle96** [comment]
I Think the script automatically seeded our testUsers, thats why you were able to log in with these credentials. I see that it is not clear enough in the documentation and will fix it in the future. Thanks for your testing :)

**Comment by SLINIcraftet204** [comment]
Hey, no problem. If I find any errors or other things that are not normal, I will report it here :)
Thanks for the help.
