### ISSUE TITLE
npm is not installed and can't be installed with and from the installscript

### ISSUE THREAD

**Issue by SLINIcraftet204** [artwork-software/artwork#516]
Hey, me again sorry xD

I have now another Problem, I'am trying to install Artwork with the ubuntu-install.sh Script again on a fresh instance but after the Script finisches, 2 lines are beeing printed out with: npm not found, try install it. (obviously the last two npm commands in the Script were failing)

Now when I try to install it manually there are many Broken Node Packages. (Screenshot)
![grafik](https://github.com/artwork-software/artwork/assets/45763476/2e523e91-1feb-4fb6-a408-dbfbc20a37f2)

Is something wrong on my End or is something broken in the Script 🤔

**Comment by Sophiensaele** [comment]
There is nodejs missing.

````bash
sudo apt update
sudo apt install nodejs
```


But actually its part of the install skript.
https://github.com/artwork-software/artwork/blob/main/ubuntu-install.sh


 **Create a keyring directory**:
   ```bash
   sudo mkdir -p /etc/apt/keyrings
   ```
 **Download and save the GPG key**:
   ```bash
   sudo curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
   ```

**Add the repository entry**:
   ```bash
   sudo echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
   ```

After these steps, update your system and install Node.js:
```bash
sudo apt update
sudo apt install nodejs
```

**Comment by updatedData** [comment]
Hi, I'm the guy who made the script. 

If you have troubles like this it's very helpful if you tell us about your distribution and version as depending on the operation system different tweaks are neccessary. 

We currently locked the installation for Node to Node 18 due to our dependency on Soketi, which in turn has a dependency on uWebSockets.js . You can have a look at https://docs.soketi.app/getting-started/installation/cli-installation#installing-with-npm for more informations regarding this.

It's also highly recommended to use the npm packages which comes bundled with the Node binaries, so I would suggest to uninstall your npm installation before installing Node to avoid further complications.

Kind regards

**Comment by SLINIcraftet204** [comment]
Hello,

thanks for the Comments. The funny thing is Nodejs 18 is installed from the script but npm not and it's a _fresh Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-107-generic x86_64)_ OS.

here my shell:
![grafik](https://github.com/artwork-software/artwork/assets/45763476/2184c513-5e63-4439-b391-a9c341e0ac4e)

**Comment by SLINIcraftet204** [comment]
Good morning,

I have now tested a bit again and found out that NodeJS and NPM were not installed by the script. I was able to solve the problem for myself by installing the NPM package first on a completely fresh Ubuntu 22.04 jammy x86_64 Linux 5.15.0-112-generic installation and then running the script. Now it's working fine.
